CREATE TABLE BOOKS(
BOOK_ID INT ,
TITLE VARCHAR(100),
AuthorID INT ,
PublishedYear INT,
CopiesAvailable  INT ,
BookCategory VARCHAR(70));

SELECT * FROM BOOKS;

CREATE TABLE AUTHORS(
AuthorID INT ,
FirstName  VARCHAR(40),
LastName   VARCHAR(40),
BirthYear  INT);

SELECT * FROM AUTHORS;

INSERT INTO BOOKS (BOOK_ID,TITLE,AuthorID,PublishedYear,CopiesAvailable,BookCategory)
VALUES(1,'SHOW HISTORY', 10, 1990, 20,'HISTORY'),
       (2,'BE FIT', 11, 1991, 18,'HEALTH'),
	   (3,'LIFE', 12, 1992, 17,'ART'),
	   (4,'CRAETIVE', 13, 1993, 15,'DESIGN'),
	   (5,'WORK', 14, 1994, 12,'BUSINESS');

	   
INSERT INTO AUTHORS(AuthorID,FirstName,LastName,BirthYear)
VALUES (10,'JOIN','MM',1880),
       (11,'MARK','KK',1882),
	   (12,'TEE','TT',1885),
	   (13,'OOE','OO',1881),
	   (14,'ZEE','ZZ',1884);

	 
SELECT * FROM BOOKS
INNER JOIN AUTHORS ON AUTHORS.AuthorID=BOOKS.AuthorID;

SELECT MIN(CopiesAvailable)FROM BOOKS;
SELECT MAX(CopiesAvailable) FROM BOOKS;

SELECT AVG(PublishedYear) FROM BOOKS;
SELECT COUNT(*) FROM BOOKS;

TRUNCATE TABLE BOOKS;

ALTER TABLE AUTHORS ADD EMAIL VARCHAR(50);
ALTER TABLE AUTHORS ADD PHINE_NUMBER INT ;

SELECT MIN(BirthYear) FROM AUTHORS;
SELECT MAX(BirthYear) FROM AUTHORS;
SELECT AVG(BirthYear) FROM AUTHORS;
SELECT COUNT (*) FROM AUTHORS;